export default {
    menu: {
        home: 'Home',
        login: 'Login',
        register: 'Register',
        server: 'Server',
        logout: 'Logout'
    },
    errors: {
        unknown: 'Unknown error',
        passwordNotMatching: 'Password do not match',
    },
    registration: {
        title: "Register",
        username: "Username",
        email: "Email",
        password: "New password",
        repeat_password: "Repeat password",
        invite_code: "Invite code",
        button: "Register",
    },
    login: {
        title: 'Login',
        username: 'Username',
        password: 'Password',
        button: 'Login'
    },
    validate: {
        accountValidated: 'Your account is now validated',
        connect: 'You can now login with the username'
    },
    my_profile: {
        account: {
            tab_name: 'My account',
            current_password: 'Current password',
            new_password: 'New password',
            update: 'Save',
            success: 'Profile has been successfully updated',
        },
        tokens: {
            tab_name: 'Connected devices',
            logged_at: 'Logged in at ',
            revoked_at: 'Revoked at',
            last_seen: 'Last seen',
            never: 'Never',
            on: 'on',
            revoke_dialog: {
                title: 'Revoke a token',
                text: 'Revoking this token will disconnect you from all devices / app using it.',
                revoke: 'Revoke',
                cancel: 'Cancel'
            }
        },
        sharex: {
            tab_name: 'ShareX'
        }
    },
    server_settings: {
        invite: {
            tab_name: "Invite code",
            code: "Invite code",
            generate: "Generate",
            list: {
                generated_by: 'Generated by',
                on: 'On',
            },
            delete_dialog: {
                title: 'Remove an invite code',
                text: 'Removing this invite code will prevent anyone from using it to register.',
                remove: 'Remove',
                cancel: 'Cancel'
            }
        }
    }
};