version: "3.8"

services:
    node:
        image: node:15.6-alpine
        restart: unless-stopped
        command: yarn start
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - 8080:3000

    mail:
        image: mailhog/mailhog
        ports:
            - 8025:8025
            - 1025:1025
