    -- As DB admin:
    -- CREATE EXTENSION IF NOT EXISTS citext;  
    -- CREATE EXTENSION IF NOT EXISTS pgcrypto;  

    DROP TABLE INVITATION_CODE;
    DROP TABLE LOGIN_TOKENS;
    DROP TABLE RATE_LIMITER;
    DROP TABLE LOGIN_ATTEMPT;
    DROP TABLE MEDIAS;
    DROP TABLE FOLDERS;
    DROP TABLE APPUSER;
    DROP TABLE DBVERSION;

    CREATE TABLE DBINFO (
        DBVERSION INTEGER
    );

    INSERT INTO DBVER (DBVERSION) VALUES (1);

    CREATE TABLE APPUSER (
        ID               SERIAL        PRIMARY KEY,
        CREATED_AT       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
        USERNAME         CITEXT        UNIQUE,
        EMAIL            CITEXT        UNIQUE,
        ROLE             INTEGER       DEFAULT 0,
        PASSWORD         VARCHAR(1024),
        VALIDATED        BOOL          DEFAULT false,
        VALIDATION_TOKEN VARCHAR(36)   DEFAULT gen_random_uuid(),
        INVITED_BY       INTEGER       REFERENCES APPUSER(ID)
    );

    CREATE TABLE FOLDERS (
        ID            SERIAL        PRIMARY KEY,
        CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
        CREATOR       INTEGER       REFERENCES APPUSER(ID),
        FOLDER_NAME   VARCHAR(30),
        PARENT_FOLDER INTEGER       REFERENCES FOLDERS(ID) DEFAULT NULL,
        PARENT_PATH   VARCHAR(4096), -- THINK TO UPDATE THIS FIELD EVERYTIME THE USER RENAME A FOLDER OR MOVE A FILE TO ANOTHER ONE
                                     -- UGLY BUT MANDATORY TO NOT MAKE 1k REQUEST EACH TIME A USER IS IN A FOLDER TO BUILD THE PATH
        CONSTRAINT unique_subfolder UNIQUE(FOLDER_NAME,PARENT_FOLDER,CREATOR)
    );

    CREATE TABLE MEDIAS (
        ID         SERIAL         PRIMARY KEY,
        CREATED_AT TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
        TITLE      VARCHAR(128),
        URL_ID     VARCHAR(30),
        DESCRIPT   VARCHAR(1024),
        VISIBILITY INTEGER,
        CREATOR    INTEGER        REFERENCES APPUSER(ID),
        PARENT     INTEGER        REFERENCES FOLDERS(ID) DEFAULT NULL,
        THUMBNAIL  TEXT,
        EXT        VARCHAR(8)
    );

    CREATE TABLE LOGIN_ATTEMPT (
        ID           INTEGER      REFERENCES APPUSER(ID),
        CREATED_AT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
        IP           VARCHAR(45),
        PRIMARY KEY (ID, CREATED_AT)
    );

    CREATE TABLE LOGIN_TOKENS (
        ID         SERIAL PRIMARY KEY UNIQUE,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ID_USR     INTEGER REFERENCES APPUSER(ID),
        TOKEN      UUID DEFAULT gen_random_uuid() UNIQUE,
        IP         VARCHAR(45),
        REVOKED    BOOL DEFAULT false,
        REVOKED_AT TIMESTAMP
    );

    CREATE TABLE RATE_LIMITER (
        IP VARCHAR(45) PRIMARY KEY UNIQUE,
        STARTING_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        AMT_REQ INT
    );

    CREATE TABLE INVITATION_CODE (
        ID SERIAL PRIMARY KEY UNIQUE,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        GENERATED_BY INTEGER REFERENCES APPUSER(ID),
        CODE VARCHAR(32)
    );