-- As DB admin:
-- CREATE EXTENSION IF NOT EXISTS citext;  
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;  


DROP TABLE LOGIN_TOKENS;
DROP TABLE RATE_LIMITER;
DROP TABLE LOGIN_ATTEMPT;
DROP TABLE PICTURES;
DROP TABLE APPUSER;

CREATE TABLE APPUSER (
    ID         SERIAL        PRIMARY KEY,
    CREATED_AT TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    USERNAME   CITEXT        UNIQUE,
    EMAIL      CITEXT        UNIQUE,
    PASSWORD   VARCHAR(1024),
    VALIDATED  BOOL          DEFAULT false,
    VALIDATION_TOKEN VARCHAR(36) DEFAULT gen_random_uuid()
);

-- Default password is 'password'
INSERT INTO APPUSER (EMAIL, USERNAME, PASSWORD) VALUES ('admin@scinna.dev', 'admin', '$argon2id$v=19$m=65536,t=3,p=2$D1hPKoAbrexDtJd6uEf3Cg$d1puA1YPJgUkvvTaotKpRWOT2xIMMIUknyl6IeWJsfQ');

CREATE TABLE PICTURES (
    ID         SERIAL         PRIMARY KEY,
    CREATED_AT TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    TITLE      VARCHAR(128),
    URL_ID     VARCHAR(30),
    DESCRIPT   VARCHAR(1024),
    VISIBILITY INTEGER,
    CREATOR    INTEGER        REFERENCES APPUSER(ID),
    EXT        VARCHAR(8)
);

CREATE TABLE LOGIN_ATTEMPT (
    ID           INTEGER      REFERENCES APPUSER(ID),
    CREATED_AT   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    IP           VARCHAR(45),
    PRIMARY KEY (ID, CREATED_AT)
);

CREATE TABLE LOGIN_TOKENS (
    ID         SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_USR     INTEGER REFERENCES APPUSER(ID),
    TOKEN      UUID DEFAULT gen_random_uuid() UNIQUE,
    IP         VARCHAR(45),
    REVOKED    BOOL DEFAULT false,
    REVOKED_AT TIMESTAMP
);

CREATE TABLE RATE_LIMITER (
    IP VARCHAR(45) PRIMARY KEY UNIQUE,
    STARTING_TIME TIMESTAMP,
    AMT_REQ INT
)