name: Docker Image CI

on:
    create:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.actor == 'oxodao'
        steps:
        - uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login do DH
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Building docker image
          id: docker_build
          uses: docker/build-push-action@v2
          with:
              push: true
              tags: scinna/server:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

